### ISSUE TITLE
Mailable preview doesn't seem to pick up User model in the construct as a parameter

### ISSUE THREAD

**Issue by jwktje** [beyondcode/invoker-community#19]
------
**OS**: darwin
**Invoker Version**: 2.0.1
**PHP Binary**: /Applications/MAMP/bin/php/php7.4.12/bin/php
**Route**: /mails/details?class=App%5CMail%5CGuestCreated&project=remote-g7ePgpAkZYrjoLikt1kMZz

**Error**:
```
ArgumentCountError 

  Too few arguments to function App\Mail\GuestCreated::__construct(), 0 passed and exactly 1 expected

  at code/app/Mail/GuestCreated.php:22
     18▕      * Create a new message instance.
     19▕      * @param  \App\User $user
     20▕      * @return void
     21▕      */
  ➜  22▕     public function __construct(User $user)
     23▕     {
     24▕         $this->user = $user;
     25▕     }
     26▕

  1   [internal]:0
      App\Mail\GuestCreated::__construct()

  2   phar:///tmp/invoker.phar/src/Actions/GetMailPreviewAction.php:30
      ReflectionClass::newInstanceArgs()
```

**Comment by mpociot** [comment]
Do you see an input/dropdown field on your input field for the Mailable?

**Comment by jwktje** [comment]
Nope. I tried changing my code around but can't get a dropdown to appear. Do you have a working example of a mailable? Maybe I'm doing something stupid on my end. The Invoker screen looks like this: 

<img width="1217" alt="Screenshot 2021-02-02 at 10 41 20" src="https://user-images.githubusercontent.com/4722137/106581477-31580b80-6543-11eb-8531-372b229e540f.png">

**Comment by mpociot** [comment]
This is a dummy mail that works for me:

```php
<?php

namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;
use App\User;

class SupportRequest extends Mailable
{
    use Queueable, SerializesModels;

    public $message;
    public $user;

    public function __construct($message, User $user)
    {
        $this->message = $message;
        $this->user = $user;
    }

    public function build()
    {
        return $this->markdown('emails.support-request')
            ->with([
                'supportRequest' => $this->message,
                'user' => $this->user,
            ]);
    }
}
```

And this is how it looks like in Invoker

![image](https://user-images.githubusercontent.com/804684/106582821-b1cb3c00-6544-11eb-8d33-53ca89e0d471.png)

**Comment by mpociot** [comment]
One more thing: Could you tell me the PHP version that you're using?

**Comment by jwktje** [comment]
I'm on Mac using the following PHP version bundled with MAMP pro (copied over after using `which php`):
`/Applications/MAMP/bin/php/php7.4.12/bin/php`

Using your code I get the same result. An empty screen in Invoker.
This is some console output that might be relevant.
```
renderer.js:1 TypeError: Cannot read property 'length' of undefined
    at c.<anonymous> (renderer.js:6)
    at c.n._render (renderer.js:6)
    at c.e (renderer.js:6)
    at Fa.get (renderer.js:6)
    at new Fa (renderer.js:6)
    at renderer.js:6
    at c.or.$mount (renderer.js:6)
    at c.or.$mount (renderer.js:6)
    at init (renderer.js:6)
    at o (renderer.js:1)
Y @ renderer.js:1
G @ renderer.js:1
U @ renderer.js:1
n._render @ renderer.js:6
e @ renderer.js:6
Fa.get @ renderer.js:6
Fa @ renderer.js:6
(anonymous) @ renderer.js:6
or.$mount @ renderer.js:6
or.$mount @ renderer.js:6
init @ renderer.js:6
o @ renderer.js:1
l @ renderer.js:6
o @ renderer.js:6
(anonymous) @ renderer.js:6
n._update @ renderer.js:6
e @ renderer.js:6
Fa.get @ renderer.js:6
Fa @ renderer.js:6
(anonymous) @ renderer.js:6
or.$mount @ renderer.js:6
or.$mount @ renderer.js:6
init @ renderer.js:6
l @ renderer.js:6
o @ renderer.js:6
v @ renderer.js:6
k @ renderer.js:6
v @ renderer.js:6
k @ renderer.js:6
(anonymous) @ renderer.js:6
n._update @ renderer.js:6
e @ renderer.js:6
Fa.get @ renderer.js:6
Fa.run @ renderer.js:6
Kn @ renderer.js:1
(anonymous) @ renderer.js:1
X @ renderer.js:1
Promise.then (async)
ha @ renderer.js:6
J @ renderer.js:1
(anonymous) @ renderer.js:6
Fa.update @ renderer.js:6
ta.notify @ renderer.js:6
set @ renderer.js:1
setOpenedMail @ renderer.js:6
wrappedMutationHandler @ /Applications/Invoker.app/Contents/Resources/app.asar/node_modules/vuex/dist/vuex.common.js:842
commitIterator @ /Applications/Invoker.app/Contents/Resources/app.asar/node_modules/vuex/dist/vuex.common.js:464
(anonymous) @ /Applications/Invoker.app/Contents/Resources/app.asar/node_modules/vuex/dist/vuex.common.js:463
_withCommit @ /Applications/Invoker.app/Contents/Resources/app.asar/node_modules/vuex/dist/vuex.common.js:622
commit @ /Applications/Invoker.app/Contents/Resources/app.asar/node_modules/vuex/dist/vuex.common.js:462
boundCommit @ /Applications/Invoker.app/Contents/Resources/app.asar/node_modules/vuex/dist/vuex.common.js:407
setMail @ renderer.js:6
click @ renderer.js:6
K @ renderer.js:1
o @ renderer.js:1
Ur.t._wrapper @ renderer.js:1
Show 7 more frames
/Applications/Invoker.app/Contents/Resources/app.asar/node_modules/vue-router/dist/vue-router.common.js:1960 Uncaught (in promise) Error: Redirected when going from "/mails/details?class=App%5CMail%5CSupportRequest&project=remote-g7ePgpAkZYrjoLikt1kMZz" to "/mails/details" via a navigation guard.
    at createRouterError (/Applications/Invoker.app/Contents/Resources/app.asar/node_modules/vue-router/dist/vue-router.common.js:1960)
    at createNavigationRedirectedError (/Applications/Invoker.app/Contents/Resources/app.asar/node_modules/vue-router/dist/vue-router.common.js:1919)
    at /Applications/Invoker.app/Contents/Resources/app.asar/node_modules/vue-router/dist/vue-router.common.js:2268
    at renderer.js:6
    at iterator (/Applications/Invoker.app/Contents/Resources/app.asar/node_modules/vue-router/dist/vue-router.common.js:2254)
    at step (/Applications/Invoker.app/Contents/Resources/app.asar/node_modules/vue-router/dist/vue-router.common.js:1900)
    at runQueue (/Applications/Invoker.app/Contents/Resources/app.asar/node_modules/vue-router/dist/vue-router.common.js:1908)
    at HashHistory.confirmTransition (/Applications/Invoker.app/Contents/Resources/app.asar/node_modules/vue-router/dist/vue-router.common.js:2284)
    at HashHistory.transitionTo (/Applications/Invoker.app/Contents/Resources/app.asar/node_modules/vue-router/dist/vue-router.common.js:2154)
    at HashHistory.push (/Applications/Invoker.app/Contents/Resources/app.asar/node_modules/vue-router/dist/vue-router.common.js:2624)
```

**Comment by chrispage1** [comment]
Hi,

I'm getting the same thing with my installation. Marcel I've just tried copying your mail template to no avail.

```
Symfony\Component\Debug\Exception\FatalThrowableError  : Too few arguments to function App\Mail\Test::__construct(), 0 passed and exactly 2 expected

  at /Volumes/Projects/Sites/example-project/app/Mail/Test.php:17
    13| 
    14|     public $message;
    15|     public $user;
    16| 
  > 17|     public function __construct($message, User $user)
    18|     {
    19|         $this->message = $message;
    20|         $this->user = $user;
    21|     }

  Exception trace:

  1   App\Mail\Test::__construct()
      [internal]:0

  2   ReflectionClass::newInstanceArgs([])
      phar:///Applications/Invoker.app/Contents/Resources/invoker.phar/src/Actions/GetMailPreviewAction.php:30

  Please use the argument -v to see more details.
```

Within the application I am getting no option to populate the parameters

![image](https://user-images.githubusercontent.com/2487374/106618613-8dcd2200-6567-11eb-9eb8-cd2524fafa7c.png)

**Comment by chrispage1** [comment]
I've just tested it on a clean Laravel install and it works no problem - so perhaps a factor here.

**Comment by jwktje** [comment]
I'm testing on Laravel 8.0. What versions did you test?

**Comment by chrispage1** [comment]
The test I ran was on 8.26.1 but the actual project I'm working on is 6.20.16

**Comment by corsair** [comment]
I was recommended by Sebastian to comment here. I'm also experiencing this issue on ``Laravel v8.22.1`` and ``PHP 8.0.1`` and on ``MacOS (10.15.7)``.

My Mailable uses two parameters, both of which are Eloquent models.
```php
public function __construct(User $user, SupportRequest $support)
```

No inputs are displayed.
![image](https://user-images.githubusercontent.com/1847891/106734958-7f632280-65c8-11eb-97b0-41a3d8a8158a.png)

**Comment by mpociot** [comment]
It would be great if one of you could share a (redacted) version of a mailable that is not working so that I can reproduce this issue.

**Comment by jwktje** [comment]
Sure, no problem. I'll attach it below. However weirdly your working example didn't work for me either. So I feel like the issue isn't in the code of the Mailable. But rather a version of some dependency maybe.

```
<?php

namespace App\Mail;

use App\User;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;

class GuestCreated extends Mailable
{
    use Queueable, SerializesModels;

    public $user;

    /**
     * Create a new message instance.
     * @param  \App\User $user
     * @return void
     */
    public function __construct(User $user)
    {
        $this->user = $user;
    }

    /**
     * Build the message.
     *
     * @return $this
     */
    public function build()
    {
        return $this->subject('Gast aangemaakt')->markdown('mail.guestcreated')->with(['user' => $this->user]);
    }
}

```

**Comment by mpociot** [comment]
Thank you, @jwktje 

Unfortunately, I wasn't able to reproduce it with your mail either.

Could you please try and use this PHAR file instead? It should show you debug information/errors when trying to parse the mails/opening the project.

To use it, please copy it to:

```
cp invoker.phar /Applications/Invoker.app/Contents/Resources/invoker.phar
```

I had to zip the PHAR file, as GitHub would otherwise not allow me to upload it :)

That would help me a lot to figure out what is going on!

[invoker.phar.zip](https://github.com/beyondcode/invoker-community/files/5918011/invoker.phar.zip)

**Comment by jwktje** [comment]
I'm on it! Will update this comment asap

**Comment by mpociot** [comment]
Thank you very much.
Huh okay...so PHP is unable to reflect your mailable constructor 🤔 
Could you try removing the docblock and see if that fixes anything?

**Comment by jwktje** [comment]
Okay I tried that just now but still get an error. I'm pretty sure it's the same one but here it is regardless: 


            
------
**OS**: darwin
**Invoker Version**: 2.0.1
**PHP Binary**: /Applications/MAMP/bin/php/php7.4.12/bin/php
**Route**: /project/placeholder?project=remote-g7ePgpAkZYrjoLikt1kMZz

**Error**:
```
LogicException 

  Invalid value

  at phar:///tmp/invoker.phar/vendor/nikic/php-parser/lib/PhpParser/BuilderHelpers.php:143
    139▕                 }
    140▕             }
    141▕             return new \_HumbugBoxbfad15e2f516\PhpParser\Node\Expr\Array_($items);
    142▕         } else {
  ➜ 143▕             throw new \LogicException('Invalid value');
    144▕         }
    145▕     }
    146▕     public static function normalizeDocComment($docComment) : \_HumbugBoxbfad15e2f516\PhpParser\Comment\Doc
    147▕     {

      [2m+15 vendor frames [22m
  16  phar:///tmp/invoker.phar/src/Factories/MailItem.php:26
      _HumbugBoxbfad15e2f516\Roave\BetterReflection\Reflection\ReflectionClass::getConstructor()

  17  phar:///tmp/invoker.phar/src/Factories/MailItem.php:20
      _HumbugBoxbfad15e2f516\Invoker\Factories\MailItem::getParameters()
```

**Comment by corsair** [comment]
Utilizing the debug .phar, I'm also getting the same error. I've also removed and added the comment block to no avail.
------
**OS**: darwin
**Invoker Version**: 2.0.1
**PHP Binary**: /usr/local/bin/php
**Route**: /project/placeholder?project=local-dAGSp4gLWSb1wd9je4h2QU

**Error**:
```
LogicException 

  Invalid value

  at phar:/Applications/Invoker.app/Contents/Resources/invoker.phar/vendor/nikic/php-parser/lib/PhpParser/BuilderHelpers.php:143
    139▕                 }
    140▕             }
    141▕             return new \_HumbugBoxbfad15e2f516\PhpParser\Node\Expr\Array_($items);
    142▕         } else {
  ➜ 143▕             throw new \LogicException('Invalid value');
    144▕         }
    145▕     }
    146▕     public static function normalizeDocComment($docComment) : \_HumbugBoxbfad15e2f516\PhpParser\Comment\Doc
    147▕     {

      [2m+15 vendor frames [22m
  16  phar:/Applications/Invoker.app/Contents/Resources/invoker.phar/src/Factories/MailItem.php:26
      _HumbugBoxbfad15e2f516\Roave\BetterReflection\Reflection\ReflectionClass::getConstructor()

  17  phar:/Applications/Invoker.app/Contents/Resources/invoker.phar/src/Factories/MailItem.php:20
      _HumbugBoxbfad15e2f516\Invoker\Factories\MailItem::getParameters("App\Mail\Custom")
```

Here is my Mailable:
```php
<?php

namespace App\Mail;

use App\Models\SupportRequest;
use App\Models\User;
use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;

class Support extends Mailable
{
    use Queueable, SerializesModels;

    private $user;
    private $support;
    private $helpRequest;
    private $response;
    private $title;

    public function __construct(User $user, SupportRequest $support)
    {
        $this->user = $user;
        $this->helpRequest = (string) $support->request;
        $this->response = (string) $support->response;
        $this->title = sprintf('RE: %s', $support->subject);
    }

    /**
     * Build the message.
     *
     * @return $this
     */
    public function build()
    {
        return $this->from('tyler@teslascope.com')
            ->view('emails.support')
            ->with([
                'user' => $this->user,
                'helpRequest' => $this->helpRequest,
                'response' => $this->response,
                'title' => $this->title
            ]);
    }
}
```

Interestingly, it seems that the error is occurring because of another Mailable (Custom)?
```php
    /**
     * Create a new message instance.
     *
     * @param User $user
     */
    public function __construct(User $user, $content, $title, $subtitle)
    {
        $this->user = $user;
        $this->content = $content;
        $this->title = $title;
        $this->subtitle = $subtitle;
    }
```

**Comment by jwktje** [comment]
@corsair I just now noticed your comment earlier. And yes, to add to that, my project was also moved over from 6 -> 7 -> 8. So maybe when following the upgrade guides some internal parts are not updated fully and this is why it is tripping up Invoker? I will test with a fresh laravel install to check this.

**Comment by mpociot** [comment]
Wow that's super weird...No idea what could be causing this when upgrading 🤔 

I also built another phar file that uses a different way to get the mail constructor parameters, maybe this fixes it already :)
It would be awesome if you could find the time to try this one out as well @jwktje 

[invoker.phar.zip](https://github.com/beyondcode/invoker-community/files/5918430/invoker.phar.zip)

**Comment by corsair** [comment]
@mpociot Here's mine! (If that's alright)


            
------
**OS**: darwin
**Invoker Version**: 2.0.1
**PHP Binary**: /usr/local/bin/php
**Route**: /project/placeholder?project=local-dAGSp4gLWSb1wd9je4h2QU

**Error**:
```
Error 

  Call to undefined method ReflectionParameter::getDocBlockTypeStrings()

  at phar:/Applications/Invoker.app/Contents/Resources/invoker.phar/src/Factories/MailItemParameter.php:17
     13▕     {
     14▕         $type = $parameter->getType();
     15▕         if (\is_null($type)) {
     16▕             try {
  ➜  17▕                 $types = $parameter->getDocBlockTypeStrings();
     18▕                 $type = \array_pop($types);
     19▕             } catch (\Exception $e) {
     20▕                 $type = null;
     21▕             }

  1   phar:/Applications/Invoker.app/Contents/Resources/invoker.phar/src/Factories/MailItem.php:28
      _HumbugBox49a844ccc197\Invoker\Factories\MailItemParameter::fromReflectionParameter(Object(ReflectionParameter))

  2   [internal]:0
      _HumbugBox49a844ccc197\Invoker\Factories\MailItem::_HumbugBox49a844ccc197\Invoker\Factories\{closure}(Object(ReflectionParameter))
```

**Comment by mpociot** [comment]
@corsair Ah damn, that was my fault. Here's the fixed phar - as yours still contained an error (sorry)

[invoker.phar.zip](https://github.com/beyondcode/invoker-community/files/5918534/invoker.phar.zip)

**Comment by jwktje** [comment]
@mpociot I just tried that one and I'm getting the same result sadly. In the meantime I'll look through the upgrade guides again thoroughly to see if there is a logical reason for a migrated project to fail


            
------
**OS**: darwin
**Invoker Version**: 2.0.1
**PHP Binary**: /Applications/MAMP/bin/php/php7.4.12/bin/php
**Route**: /project/placeholder?project=remote-g7ePgpAkZYrjoLikt1kMZz

**Error**:
```
LogicException 

  Invalid value

  at phar:///tmp/invoker.phar/vendor/nikic/php-parser/lib/PhpParser/BuilderHelpers.php:143
    139▕                 }
    140▕             }
    141▕             return new \_HumbugBoxbfad15e2f516\PhpParser\Node\Expr\Array_($items);
    142▕         } else {
  ➜ 143▕             throw new \LogicException('Invalid value');
    144▕         }
    145▕     }
    146▕     public static function normalizeDocComment($docComment) : \_HumbugBoxbfad15e2f516\PhpParser\Comment\Doc
    147▕     {

      [2m+15 vendor frames [22m
  16  phar:///tmp/invoker.phar/src/Factories/MailItem.php:26
      _HumbugBoxbfad15e2f516\Roave\BetterReflection\Reflection\ReflectionClass::getConstructor()

  17  phar:///tmp/invoker.phar/src/Factories/MailItem.php:20
      _HumbugBoxbfad15e2f516\Invoker\Factories\MailItem::getParameters()
```

**Comment by corsair** [comment]
> @mpociot I just tried that one and I'm getting the same result sadly. In the meantime I'll look through the upgrade guides again thoroughly to see if there is a logical reason for a migrated project to fail
> 
> UPDATE:
> 
> Possible breakthrough. The project that is failing was connecting over SSH to the Homestead Vagrant box. When I open it just on the filesystem the Mailable opens correctly but I get an (expected) SQL error because it can't find the Users in the DB because the .env is configured for inside Homestead. Does this also reflect your situation @corsair ? And does this make sense to you @mpociot ?
> 
> UPDATE 2:
> Maybe if we could provide different DB connection information for Invoker so it can connect to inside the Vagrant box, we would be done. Because using the port 33060 would allow for that
> 
> UPDATE 3:
> Changing my DB_PORT to 33060 inside .env fixes the bug completely in Invoker! So yay! But obviously this breaks the application. So at least now we know this is a Homestead/DB_PORT issue rather than a Laravel migration issue

This sadly differs from my case as this issue is occurring locally (so no SSH) and on production (via SSH).

**Comment by corsair** [comment]
> @corsair Ah damn, that was my fault. Here's the fixed phar - as yours still contained an error (sorry)
> 
> [invoker.phar.zip](https://github.com/beyondcode/invoker-community/files/5918534/invoker.phar.zip)

This fixed it!!

**Comment by mpociot** [comment]
> And does this make sense to you @mpociot ?
Yeah, the PHAR file only gets uploaded once per version (via SSH) - so when you manually modify the PHAR, it doesn't upload it again to the SSH server. You can delete the phar using:

```
rm /tmp/invoker.phar
```

This will force Invoker to reupload it when connecting.

@corsair Did you try my second PHAR file (this one: https://github.com/beyondcode/invoker-community/issues/19#issuecomment-772485569) ?

**Comment by corsair** [comment]
Thank YOU for the wonderful support and for getting this resolved. And to @jwktje as well.

Confirmation of it working:
![image](https://user-images.githubusercontent.com/1847891/106751925-b9d7ba00-65de-11eb-8d0f-b9b369eeeaa8.png)

**Comment by jwktje** [comment]
Awesome you guys! So it was the combination of the new PHAR that actually solved it. Which made me stumble upon this Homestead port issue. @mpociot Thanks a bunch! How can we easily solve this port problem? Should I create another issue for this?
